colorscheme Molokai
"set guifont=Andale\ Mono:h13
set guifont=Source\ Code\ Pro\ Light\ for\ Powerline:h12
set transparency=5
set linespace=0
" underline on current line
highlight CursorLine gui=underline guifg=NONE guibg=NONE
set guioptions-=T