colorscheme iceberg
"set guifont=Andale\ Mono:h13
"set guifont=Source\ Code\ Pro\ for\ Powerline:h13
set guifont=Menlo\ Regular:h12
set transparency=5
set linespace=0
" underline on current line
highlight CursorLine gui=underline guifg=NONE guibg=NONE
set guioptions-=T
set formatoptions=q

" 縦幅　デフォルトは24
set lines=60
" 横幅　デフォルトは80
set columns=160